version: '3'
services:
  react-app:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - ./entrypoint.sh:/entrypoint.sh:ro
    # entrypoint: bash -c ./entrypoint.sh
    env_file:
      - ./.env
    command: bash -c 'cd app && yarn start'
    ports:
      - "3000:3000"
    tty: True